#!/bin/bash

title='Not Playing'
convert ~/.conky/conkygoogleplaymusic/GPM ~/.conky/conkygoogleplaymusic/gmdmp_art


if pidof -x "$(basename 'Google Play Music Desktop Player')" > /dev/null
then

art=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.song.albumArt')

so=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.song.artist, .song.title' | sed ':a;N;$!ba;s/\n/ \- /')

status=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.playing')

time_cur=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.time.current')
time_tot=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.time.total')

secs_cur=($time_cur/1000)
time_cur2=$(printf '%02d:%02d\n' $(($secs_cur%3600/60)) $(($secs_cur%60)))

secs_tot=($time_tot/1000)
time_tot2=$(printf '%02d:%02d\n' $(($secs_tot%3600/60)) $(($secs_tot%60)))

title=$so

if
[ "$status" = "false" ];
then
title=$so echo 'PAUSED'
fi

curl -o ~/.conky/conkygoogleplaymusic/gmdmp_art "$art"

echo "$title" "-" "(""$time_tot2"")"

else

echo "$title"

fi
 
