#!/bin/bash

if pidof -x "$(basename 'Google Play Music Desktop Player')" > /dev/null
then

art=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.song.albumArt')

so=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.song.artist, .song.title' | sed ':a;N;$!ba;s/\n/ \- /')

title=$so

curl -o ~/.conky/conkygoogleplaymusic/gmdmp_art "$art"

else
title='Not Playing'
convert ~/.conky/conkygoogleplaymusic/GPM ~/.conky/conkygoogleplaymusic/gmdmp_art
fi

echo "$title"

 
