#!/bin/bash


if pidof -x "$(basename 'Google Play Music Desktop Player')" > /dev/null
then

time_cur=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.time.current')
time_tot=$(cat "$HOME/.config/Google Play Music Desktop Player/json_store/playback.json" | jq -r '.time.total')

secs_cur=($time_cur/1000)
time_cur2=$(printf '%02d:%02d\n' $(($secs_cur%3600/60)) $(($secs_cur%60)))

secs_tot=($time_tot/1000)
time_tot2=$(printf '%02d:%02d\n' $(($secs_tot%3600/60)) $(($secs_tot%60)))


echo "$time_cur2" "/" "$time_tot2"

else
exit 0
fi
