#!/bin/bash 
st=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio)
lbc_uk='LBC UK'
lbc_london='LBC London'
plan_rock='Planet Rock'
hdr='Hard Drivin Radio'
big80s='Big 80s Metal'
kfi='KFI'
twit='TWiT.am'
ragga='Raggakings'
fivelive='5live'
radiofour='Radio 4'
radiostoke='Radio Stoke'
radio_paradise='Radio Paradise' 


station=${st}

case "$station" in 
    "$lbc_uk" )
        cp -f /home/swipe/.local/share/radiotray/lbc  /home/swipe/.local/share/radiotray/icon
;;
    "$lbc_london" )
        cp -f /home/swipe/.local/share/radiotray/lbc2  /home/swipe/.local/share/radiotray/icon
;;
    "$plan_rock" )
        cp -f /home/swipe/.local/share/radiotray/planrock  /home/swipe/.local/share/radiotray/icon
;;
    "$hdr" )
        cp -f /home/swipe/.local/share/radiotray/hdr  /home/swipe/.local/share/radiotray/icon
;;
    "$big80s" )
        cp -f /home/swipe/.local/share/radiotray/big80s  /home/swipe/.local/share/radiotray/icon
;;
    "$kfi" )
        cp -f /home/swipe/.local/share/radiotray/kfi  /home/swipe/.local/share/radiotray/icon
;;
    "$twit" )
        cp -f /home/swipe/.local/share/radiotray/twit  /home/swipe/.local/share/radiotray/icon
;;
    "$ragga" )
        cp -f /home/swipe/.local/share/radiotray/ragga  /home/swipe/.local/share/radiotray/icon
;;
    "$fivelive" )
        cp -f /home/swipe/.local/share/radiotray/5live  /home/swipe/.local/share/radiotray/icon
;;
    "$radiofour" )
        cp -f /home/swipe/.local/share/radiotray/radio4  /home/swipe/.local/share/radiotray/icon
;;
    "$radiostoke" )
        cp -f /home/swipe/.local/share/radiotray/radiostoke  /home/swipe/.local/share/radiotray/icon
;;
    "$radio_paradise" )
;;
    *)
        cp -f /home/swipe/.local/share/radiotray/radiotray  /home/swipe/.local/share/radiotray/icon
;;
esac
exit 0


