#!/bin/bash 
if pidof -x $(basename radiotray) > /dev/null 
then 
st=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio)
so=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray getCurrentMetaData| fold -s -w150) 
busqueda='(not playing)' 
cadenaextraida=${st: -13}   
if [ "$cadenaextraida" = "$busqueda" ]; 
then 
bandera='NO'   
else 
bandera="SI" 
fi 
else 
bandera="NE" 
fi 
echo $bandera 
exit 0
