#!/bin/bash 
if pidof -x $(basename radiotray-ng) > /dev/null 
then 

st=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.station')
 
so=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.title')
#rtngtitle='' 
#playing=${so: -7}
playing=''
#rtngsong=${so}
#lbcuk={st:0:6}
lbcuk='LBC UK'
radio3='Radio 3'
rp='Radio Paradise'
#kfi=${st:0:3}
kfi='KFI'

if [ "$lbcuk" = "$st" ] || [ "$radio3" = "$st" ] || [ "$rp" = "$st" ];
    then
    conkytitle=$(cat ~/.conky/conkyradiotray-ng/onair.txt)
 
elif [ "$kfi" = "$st" ] || [ "$playing" = "$so" ]
    then 
    conkytitle='No info'
    
else 
    conkytitle=$so 
fi
fi

echo "$conkytitle"
exit 0 
