#!/bin/bash 
if pidof -x $(basename radiotray-ng) > /dev/null 
then 
#st=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio)
st=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r 'station')
#so=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray getCurrentMetaData| fold -s -w150) 
so=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.title')
status='' 
artist=${so: -7}  
status2='text' 
artist2=${so:0:4} 
if [ "$artist" = "$status" ]; 
then 
title='No info'   
elif [ "$artist2" = "$status2" ]; 
then 
title='No info'  
else 
title=$so 
fi
fi
echo $title 
exit 0
