#!/bin/bash

if pidof -x $(basename radiotray-ng) > /dev/null 
then 

onair=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '//section/div/span/a[1]/text()' - | tail -c 25) 

onairtime=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '//section/div/p/span/text()' - | tail -c 25)
echo $onair > ~/.conky/conkyradiotray-ng/onair.txt
truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
echo " - " >> ~/.conky/conkyradiotray-ng/onair.txt
truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
echo $onairtime >> ~/.conky/conkyradiotray-ng/onair.txt

fi
exit 0
