#!/bin/bash

# Get lbc artist and title info
lbc()
{
onair=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '//section/div/span//text()' - | tail -c 61)


onairtime=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '//section/div/p/span/text()' - | tail -c 25)


echo $onair > /home/swipe/.conky/conkyradiotray-ng/onair.txt

truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
echo " - " >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
echo $onairtime >> /home/swipe/.conky/conkyradiotray-ng/onair.txt

exit 0
}

# Get radio artist and title info
radio3()
{

#curl -s https://www.bbc.co.uk/radio3 | xmllint --html --nowarning --xpath '//div[2]/a//text()' - | tail -c -320 | sed '/^$/d' | sed '1,10d' | sed '1,2d'| sed '5d' | sed '2,3d' | sed '4,5d' | sed '$d' | sed '/^$/d' > /home/swipe/.conky/conkyradiotray-ng/onair.txt

# Wrap 3rd line to end of second line
#sed -i ':a;N;$!ba;s/\n/ - /2g' /home/swipe/.conky/conkyradiotray-ng/onair.txt

timeslot=$(curl -s https://www.bbc.co.uk/radio3 | xmllint --html --nowarning --xpath '//div[2]/a//time/text()' - )

prog=$(curl -s https://www.bbc.co.uk/radio3 | xmllint --html --nowarning --xpath '//div[2]/a//h3/text()' - )

progname=$(curl -s https://www.bbc.co.uk/radio3 | xmllint --html --nowarning --xpath '//div[2]/a//p/text()' - )

echo $timeslot > /home/swipe/.conky/conkyradiotray-ng/onair.txt
 
truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
echo " - " >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
echo $prog >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
echo $progname >> /home/swipe/.conky/conkyradiotray-ng/onair.txt

exit 0
}

# radioparadise()
# {
# rpartist=$(awk -F '[<>]' '/artist/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
# 
# rpsongtitle=$(awk -F '[<>]' '/title/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
# 
# echo $rpartist > /home/swipe/.conky/conkyradiotray-ng/onair.txt
# 
# truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
# echo " - " >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
# truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
# echo $rpsongtitle >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
# }

# Check if LBC or Radio 3 is playing then call appropriate function
if pidof -x $(basename radiotray-ng) > /dev/null 
then 

st=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.station')
 
so=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.title')


lbcuk='LBC UK'
radio3='Radio 3'
kfi='KFI'
# rp='Radio Paradise'

if [ "$lbcuk" = "$st" ] ;
    then
    lbc
elif [ "$radio3" = "$st" ] ;
    then
    radio3
# elif [ "$rp" = "$st" ] ;
#     then
#     radioparadise   
fi
fi
