#!/bin/bash

#Populate $st with current station, $so with current artist and song and define station name variables
st=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.station')
so=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.title' | fold -s -w150)

On_LBC()
{
# Get what's on LBC
        onair=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '//section/div/span//text()' - | tail -c 61)
        onairtime=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '//section/div/p/span/text()' - | tail -c 25)
        echo "$onair" > /home/swipe/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
        echo " - " >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
        echo "$onairtime" >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
}

On_radiothree()
#Get what's on Radio 3
{
        timeslot=$(curl -s https://www.bbc.co.uk/radio3 | xmllint --html --nowarning --xpath '//div[2]/a//time/text()' - )

        prog=$(curl -s https://www.bbc.co.uk/radio3 | xmllint --html --nowarning --xpath '//div[2]/a//h3/text()' - )

        progname=$(curl -s https://www.bbc.co.uk/radio3 | xmllint --html --nowarning --xpath '//div[2]/a//p/text()' - )

        echo "$timeslot" > /home/swipe/.conky/conkyradiotray-ng/onair.txt
 
        truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
        echo " - " >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
        echo "$prog" >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
        echo "$progname" >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
}

On_radioparadise()
#Get what's on radio paradise and download cover artist
{
        #Populate $chk_art with the coverart url
        chk_art=$(awk -F '[<>]' '/coverart/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
        #Download now.xml and save local copy
        curl -o ~/.config/radiotray-ng/bookmark_icons/now.xml http://legacy.radioparadise.com/xml/now.xml
        #Populate $chk_art2 with the coverart url from local copy of now.xml
        chk_art2=$(awk -F '[<>]' '/coverart/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
            
            #Check if the coverart urls match and, if not, get new coverart and resize to 115 width
            if 
                [ "$chk_art" != "$chk_art2" ]; 
            then 
                art=$(awk -F '[<>]' '/coverart/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
                wget -O ~/.config/radiotray-ng/bookmark_icons/rp_art "$art"
                convert ~/.config/radiotray-ng/bookmark_icons/rp_art -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
            fi
        
        rpartist=$(awk -F '[<>]' '/artist/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
        rpsongtitle=$(awk -F '[<>]' '/title/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
        # echo artist and song to 
        echo "$rpartist" > /home/swipe/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
        echo " - " >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 /home/swipe/.conky/conkyradiotray-ng/onair.txt
        echo "$rpsongtitle" >> /home/swipe/.conky/conkyradiotray-ng/onair.txt
}

lbc_uk='LBC UK'
lbc_london='LBC London'
#plan_rock='Planet Rock'
kfi='KFI'
twit='TWiT.am'
fivelive='5live'
radiofour='Radio 4'
radiothree='Radio 3'
radiofourextra='Radio 4 Extra'
radiostoke='Radio Stoke'
radiokent='Radio Kent'
radio_paradise='Radio Paradise' 
ragga='Raggakings'
talkradio='TalkRadio'
talksport='talkSPORT'
talksport2='talkSPORT 2'
signal2='Signal 2'
classicfm='Classic FM'
not_playing='(not playing)'

#Check for Radio Paradise or show radiotray image if status='Playing'
station=${st}
status=''
rp='Radio Paradise'
artist=${so: -0}
cadena=${st: -14}
rpartist=$(awk -F '[<>]' '/artist/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
rpsongtitle=$(awk -F '[<>]' '/title/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
if [ "$artist" = "$status" ]; 
then
#title='radiotray icon'
#title='hashtag/radiotray'
title='radio tower icon white'
#title='black'
elif [ "$cadena" = "$rp" ]; 
then 
station='Radio Paradise'  
else 
title=$so
fi

#Check if station='(not playing)
query='(not playing)' 
output=${st: -13}   
if [ "$output" = "$query" ]; 
then 
station='(not playing)'
fi


#Read the first line of artist_title.txt for artist & song title and populate $title_read
title_read=$(head -1 ~/.conky/conkyradiotray-ng/artist_title.txt)

#linkMiniature=$(wget -U'Googlebot-Image/1.0' -qO - "www.google.co.uk/search?q=$title\&tbm=isch" | perl -pe 's!.*?<img .*?src="([^"]*)".*!$1!')

linkMiniature=$(wget -U 'Googlebot-Image/1.0' -qO - "www.google.co.uk/search?q=$title\&tbm=isch" | awk -v RS='[[:blank:]]' '/^src=/' | awk 'NR==1' | cut -c6- | sed 's/.$//')

#Check each station variable and use imagemagick convert command to resize image and copy to ~/.config/radiotray-ng/bookmark_icons/icon
case "$station" in 
    "$lbc_uk" )
        convert  ~/.config/radiotray-ng/bookmark_icons/lbc_round -resize 115 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC
;;
    "$lbc_london" )
        convert ~/.config/radiotray-ng/bookmark_icons/lbc2 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC
;;
    "$kfi" )
        convert ~/.config/radiotray-ng/bookmark_icons/kfi -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$twit" )
        convert ~/.config/radiotray-ng/bookmark_icons/twit -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$fivelive" )
        convert ~/.config/radiotray-ng/bookmark_icons/5live -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$radiofour" )
        convert ~/.config/radiotray-ng/bookmark_icons/radio4 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$radiothree" )
        convert ~/.config/radiotray-ng/bookmark_icons/radio3 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_radiothree
;;
    "$radiofourextra" )
        convert ~/.config/radiotray-ng/bookmark_icons/radio4extra -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$radiostoke" )
        convert ~/.config/radiotray-ng/bookmark_icons/radiostoke -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$radiokent" )
        convert ~/.config/radiotray-ng/bookmark_icons/radiokent -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$talkradio" )
        convert ~/.config/radiotray-ng/bookmark_icons/talkradio -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$talksport" )
        convert ~/.config/radiotray-ng/bookmark_icons/talksport -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$talksport2" )
        convert ~/.config/radiotray-ng/bookmark_icons/talksport2 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$signal2" )
        convert ~/.config/radiotray-ng/bookmark_icons/signal2 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon    
;;
    "$classicfm" )
        convert ~/.config/radiotray-ng/bookmark_icons/classicfm_round -resize 115 ~/.config/radiotray-ng/bookmark_icons/icon 
;;
#     "$plan_rock" )
#         convert  ~/.config/radiotray-ng/bookmark_icons/planrock -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
# ;;
    "$ragga" )
        convert ~/.config/radiotray-ng/bookmark_icons/ragga -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
;;
    "$radio_paradise" )
        On_radioparadise
;;
    #If status = 'not playing' don't do anything
    "$not_playing" )
;;
    #If any other case get albumart using miniatureGoogleImage
    *)
        #Check if albumart is already downloaded, if not, populate artist_title.txt with artist & song title, then download albumart and convert to icon and resize it
        if
        [ "$title_read" != "$title" ];
        then
        echo "$title" | fold -s -w80 > ~/.conky/conkyradiotray-ng/artist_title.txt
        wget -qO miniatureGoogleImage "$linkMiniature"
        convert ~/miniatureGoogleImage -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        fi
;;
esac

exit 0
