#!/bin/bash

#Populate $st with current station, $so with current artist and song and define station name variables
st=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.station')
so=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.title' | fold -s -w150)
ar=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.artist')

Onair_txt()
{
        echo $onair > ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo "   " >> ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo $onairtime >> ~/.conky/conkyradiotray-ng/onair.txt
}

On_LBC()
{
# Get what's on LBC
        #Query if guest presenter schedule is empty
        onair=$(curl -s https://ukradiolive.com/lbc-97-3 | xmllint --html --nowarning --xpath '/html/body/div[1]/div[3]/div/div[2]/div[2]/div[3]/div[1]/div[6]/div[4]/div[2]/a' - | tail -c 61 | awk -F'[><]' '{print $2}') 
        #if [[ -z "$onair" ]]; then
        #Query normal presenter schedule
        #onair=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div[1]/div[2]/p' - | tail -c 25 | awk -F'[><]' '{print $2}')
        #fi
        onairtime=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div[1]/div[2]/span' - | tail -c 21 | awk -F'[><]' '{print $2}')
        #onairtime=$(curl -s https://ukradiolive.com/lbc-97-3 | xmllint --html --nowarning --xpath '' - | tail -c 21 | awk -F'[><]' '{print $2}')
        Onair_txt
}

On_LBC_News()
{
# Get what's on LBC News
        #onair=$(curl -s https://www.lbcnews.co.uk/ | xmllint --html --nowarning --xpath '//section/div/p/span/a//text()' - | tail -c 61)
        onair=$(curl -s https://www.lbcnews.co.uk/ | xmllint --html --nowarning --xpath '//section/div/p/span//text()' - | head -c 67)
        onairtime=$(curl -s https://www.lbcnews.co.uk/ | xmllint --html --nowarning --xpath '//section/div/p/span/text()' - | tail -c 25)
        Onair_txt
}



On_Talkradio()
{
# # # Get what's on Talkradio
         onair=$(curl -s https://talk.tv/radio-player-content | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div/div/div/div/div/div[2]/div/div/div/div/div[2]/div/span' - | tail -c 60 | awk -F'[><]' '{print $2}') #| sed 's/^Morning Glory with //')
         #onairtime=$(curl -s https://talk.tv/play/talkradio | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-19) 
         
         # Check for BST or GMT
#          if [ $(date +%Z) = "BST" ]
#          then ST=1
#          else ST=0
#          fi
         
#          onairtime1=$(curl -s https://talk.tv/radio-player-content | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div/div/div/div/div/div[2]/div/div/div/div/div[1]/div/div/div[2]/div/span/text()' - | tail -c 31 | cut -c 1-8)
#          onairtime2=$(curl -s https://talk.tv/radio-player-content | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div/div/div/div/div/div[2]/div/div/div/div/div[1]/div/div/div[2]/div/span/text()' - | tail -c 31 | cut -c 11-20)
#          onairtime3=$(date -d "$onairtime1 +$ST hour" "+%l:%M%P")
#          onairtime4=$(date -d "$onairtime2 +$ST hour" "+%l:%M%P") 
#          onairtime="$onairtime3 "-" $onairtime4"
        
         onairtime=$(curl -s https://talk.tv/radio-player-content | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div/div/div/div/div/div[2]/div/div/div/div/div[1]/div/div/div[2]/div/span' - | tail -c 40 | awk -F'[><]' '{print $2}')
         Onair_txt
}

On_Talksport()
{
# # # Get what's on Talksport
         onair=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[3]/text()' - | sed 's/amp;//')
         #onairtime=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-19) 
         
         # Check for BST or GMT
         if [ $(date +%Z) = "BST" ]
         then ST=1
         else ST=0
         fi
         
         onairtime1=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-8)
         onairtime2=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 11-20)
         onairtime3=$(date -d "$onairtime1 +$ST hour" "+%l:%M%P")
         onairtime4=$(date -d "$onairtime2 +$ST hour" "+%l:%M%P") 
         onairtime="$onairtime3 "-" $onairtime4"
         Onair_txt
}

On_Talksport2()
{
# # # Get what's on Talksport2
         onair=$(curl -s https://talksport.com/play/talksport2 | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[3]/text()' - | sed 's/amp;//')
         #onairtime=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-19) 
         
         # Check for BST or GMT
         if [ $(date +%Z) = "BST" ]
         then ST=1
         else ST=0
         fi
         
         onairtime1=$(curl -s https://talksport.com/play/talksport2 | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-8)
         onairtime2=$(curl -s https://talksport.com/play/talksport2 | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 11-20)
         onairtime3=$(date -d "$onairtime1 +$ST hour" "+%l:%M%P")
         onairtime4=$(date -d "$onairtime2 +$ST hour" "+%l:%M%P") 
         onairtime="$onairtime3 "-" $onairtime4"
         Onair_txt
}

On_Timesradio()
{
# # Get what's on Timesradio - grep characters between > and </h1> and between > and </p>
        onair=$(curl -s https://www.thetimes.com/radio/live-player | xmllint --html --nowarning --xpath '/html/body/section/div/div/div[2]/div[1]/div[1]/main/h1' - | grep -o -P '(?<=>).*(?=</h1>)')
        onairtime=$(curl -s https://www.thetimes.com/radio/live-player | xmllint --html --nowarning --xpath '/html/body/section/div/div/div[2]/div[1]/div[1]/main/div/div/p' - | grep -o -P '(?<=>).*(?=</p>)')
        Onair_txt
}


On_radioparadise()
#Get what's on radio paradise and download cover artist
{
        #Populate $chk_art with the coverart url
        chk_art=$(awk -F '[<>]' '/coverart/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
        #Download now.xml and save local copy
        curl -o ~/.config/radiotray-ng/bookmark_icons/now.xml http://legacy.radioparadise.com/xml/now.xml
        #Populate $chk_art2 with the coverart url from local copy of now.xml
        chk_art2=$(awk -F '[<>]' '/coverart/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
            
            #Check if the coverart urls match and, if not, get new coverart and resize to 115 width
            if 
                [ "$chk_art" != "$chk_art2" ]; 
            then 
                art=$(awk -F '[<>]' '/coverart/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
                curl -o ~/.config/radiotray-ng/bookmark_icons/rp_art "$art"
                convert ~/.config/radiotray-ng/bookmark_icons/rp_art -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
            fi
        
        rpartist=$(awk -F '[<>]' '/artist/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml | sed 's/amp;//')
        rpsongtitle=$(awk -F '[<>]' '/title/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml | sed 's/amp;//')
        #rpartist=$(awk -F '[<>]' '/artist/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml | sed 's/amp;//')
        #rpsongtitle=$(awk -F '[<>]' '/title/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml | sed 's/amp;//')
        # echo artist and song to 
        echo "$rpartist" > ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo " - " >> ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo "$rpsongtitle" >> ~/.conky/conkyradiotray-ng/onair.txt
}

lbc_uk='LBC UK'
lbc_london='LBC London'
lbc_news='LBC News'
gb_news='GB News'
times_radio='Times Radio'
#plan_rock='Planet Rock'
radio_paradise='Radio Paradise'
radio_paradise_rock='Radio Paradise Rock'
ragga='Raggakings'
talkradio='TalkRadio'
talksport='talkSPORT'
talksport2='talkSPORT 2'
fivelive='BBC Radio 5 Live'
radiostoke='BBC Radio Stoke'
bloomr='Bloomberg Radio'
#classicfm='Classic FM'
morow='Morow'
#audiophile='Audiophile Classical'
not_playing='(not playing)'

#Check for Radio Paradise or show radiotray image if status='Playing'
station=${st}
status=''
rp='Radio Paradise'
artist=${so: -0}
cadena=${st: -14}
rpartist=$(awk -F '[<>]' '/artist/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
rpsongtitle=$(awk -F '[<>]' '/title/{print $3}' ~/.config/radiotray-ng/bookmark_icons/now.xml)
if [ "$artist" = "$status" ]; 
then
title='antenna tower icon white'
#title='free white radio tower icon-18'
elif [ "$cadena" = "$rp" ]; 
then 
station='Radio Paradise'  
else 
title=$so
#title=""$ar" "-" "$so""
fi

#Check if station='(not playing)
query='(not playing)' 
output=${st: -13}   
if [ "$output" = "$query" ]; 
then 
station='(not playing)'
fi


#Read the first line of artist_title.txt for artist & song title and populate $title_read
title_read=$(head -1 ~/.conky/conkyradiotray-ng/artist_title.txt)

#Read $title_read and substitute white spaces for '+' and '&' for '%26' and '#' for '%23' and ':' for '%3A' and ';' for '%3B' and ',' for '%2C' and '[' for '%5B' and ']' for '%5D' so google image search works on the whole string
title_search=$(echo $title_read | sed 's/ /+/g' | sed 's/&/%26/g' | sed 's/#/%23/g' | sed 's/:/%3A/g' | sed 's/;/%3B/g' | sed 's/,/%2C/g' | sed 's/\[/%5B/g' | sed 's/\]/%5D/g')

#Get the URL of $title_search, define awk record seperator as "src", select the second record with NR==2, cut up to the 6th character, then remove the last 11 characters with sed
linkMiniature=$(wget -U 'Googlebot-Image/1.0' -qO - "www.google.co.uk/search?q=$title_search\&tbm=isch" | awk -v RS='[[:blank:]]' '/^src=/' | awk 'NR==2' | cut -c6- | sed 's/.\{11\}$//')


#Check each station variable and use imagemagick convert command to resize image and copy to ~/.config/radiotray-ng/bookmark_icons/icon
case "$station" in 
    "$lbc_uk" )
        convert  ~/.config/radiotray-ng/bookmark_icons/lbc_round -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC
;;
    "$lbc_news" )
        convert  ~/.config/radiotray-ng/bookmark_icons/lbc_news -resize 135 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC_News
;;
    "$gb_news" )
        convert  ~/.config/radiotray-ng/bookmark_icons/GBN.png -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC_News
;;
    "$lbc_london" )
        convert ~/.config/radiotray-ng/bookmark_icons/lbc2 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC
;;
    "$times_radio" )
        convert ~/.config/radiotray-ng/bookmark_icons/timesradio -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Timesradio
;;
    "$talkradio" )
        convert ~/.config/radiotray-ng/bookmark_icons/TalkRadio -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Talkradio
;;
    "$talksport" )
        convert ~/.config/radiotray-ng/bookmark_icons/talksport -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Talksport
;;
    "$talksport2" )
        convert ~/.config/radiotray-ng/bookmark_icons/talksport2 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Talksport2
;;
    "$fivelive" )
        convert ~/.config/radiotray-ng/bookmark_icons/5live -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
       
;;
    "$radiostoke" )
        convert ~/.config/radiotray-ng/bookmark_icons/radiostoke -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        
;;
    "$bloomr" )
        convert ~/.config/radiotray-ng/bookmark_icons/br -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon    
;;
    "$radio_paradise" )
        On_radioparadise
;;
    #If status = 'not playing' don't do anything
    "$not_playing" )
;;
    #If any other case get albumart using miniatureGoogleImage
    *)
        #Check if albumart is already downloaded, if not, populate artist_title.txt with artist & song title, then download albumart and convert to icon and resize it
        if
        [ "$title_read" != "$title" ];
        then
        #echo "$title" | fold -s -w80 > ~/.conky/conkyradiotray-ng/artist_title.txt
        echo "$ar" - "$so" | fold -s -w80 > ~/.conky/conkyradiotray-ng/artist_title.txt
        wget -qO miniatureGoogleImage "$linkMiniature"
        convert ~/miniatureGoogleImage -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        fi
;;
esac

# Show artist and title info or "No Info"
if [ "$lbc_uk" = "$st" ] || [ "$lbc_news" = "$st" ] || [ "$lbc_london" = "$st" ] || [ "$radio_paradise" = "$st" ] || [ "$talksport" = "$st" ] || [ "$times_radio" = "$st" ] || [ "$talkradio" = "$st" ]; #|| [ "$talksport2" = "$st" ] 
    then
    conkytitle=$(cat ~/.conky/conkyradiotray-ng/onair.txt)
 
elif [ "$talkradio" = "$st" ] || [ "$playing" = "$so" ]
    then 
    conkytitle='No info'
    
else 
    conkytitle=$so
    conkyartist=$ar
    conkyspacer=" - "
fi


echo "$conkyartist""$conkyspacer""$conkytitle"

exit 0
