#!/bin/bash

#Populate $st with current station, $so with current artist and song and define station name variables
st=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.station')
so=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.title' | fold -s -w150)
ar=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.artist')

Onair_txt()
{
        echo $onair > ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo "   " >> ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo $onairtime >> ~/.conky/conkyradiotray-ng/onair.txt
}

On_LBC()
{
# Get what's on LBC
        #Query if guest presenter schedule is empty
        onair=$(curl -s https://ukradiolive.com/lbc-97-3 | xmllint --html --nowarning --xpath '/html/body/div[1]/div[3]/div/div[2]/div[2]/div[3]/div[1]/div[6]/div[4]/div[2]/a' - | tail -c 61 | awk -F'[><]' '{print $2}') 
        onairtime=$(curl -s https://www.lbc.co.uk | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div[1]/div[2]/span' - | tail -c 21 | awk -F'[><]' '{print $2}')
        #onairtime=$(curl -s https://ukradiolive.com/lbc-97-3 | xmllint --html --nowarning --xpath '' - | tail -c 21 | awk -F'[><]' '{print $2}')
        Onair_txt
}

On_LBC_News()
{
# Get what's on LBC News
        #onair=$(curl -s https://www.lbcnews.co.uk/ | xmllint --html --nowarning --xpath '//section/div/p/span/a//text()' - | tail -c 61)
        onair=$(curl -s https://www.lbcnews.co.uk/ | xmllint --html --nowarning --xpath '//section/div/p/span//text()' - | head -c 67)
        onairtime=$(curl -s https://www.lbcnews.co.uk/ | xmllint --html --nowarning --xpath '//section/div/p/span/text()' - | tail -c 25)
        Onair_txt
}

On_GB_News()
{
# Get what's on LBC News
        onair=$(qdbus com.github.radiotray_ng /com/github/radiotray_ng com.github.radiotray_ng.get_player_state | jq -r '.title')
        Onair_txt
}


On_Talkradio()
{
# # # Get what's on Talkradio
         onair=$(curl -s https://talk.tv/radio-player-content | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div/div/div/div/div/div[2]/div/div/div/div/div[2]/div/span' - | tail -c 60 | awk -F'[><]' '{print $2}') #| sed 's/^Morning Glory with //')
      
         onairtime=$(curl -s https://talk.tv/radio-player-content | xmllint --html --nowarning --xpath '/html/body/div[1]/div/div/div/div/div/div/div[2]/div/div/div/div/div[1]/div/div/div[2]/div/span' - | tail -c 40 | awk -F'[><]' '{print $2}')
         Onair_txt
}

On_Talksport()
{
# # # Get what's on Talksport
         onair=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[3]/text()' - | sed 's/amp;//')
         #onairtime=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-19) 
         
         # Check for BST or GMT
         if [ $(date +%Z) = "BST" ]
         then ST=1
         else ST=0
         fi
         
         onairtime1=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-8)
         onairtime2=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 11-20)
         onairtime3=$(date -d "$onairtime1 +$ST hour" "+%l:%M%P")
         onairtime4=$(date -d "$onairtime2 +$ST hour" "+%l:%M%P") 
         onairtime="$onairtime3 "-" $onairtime4"
         Onair_txt
}

On_Talksport2()
{
# # # Get what's on Talksport2
         onair=$(curl -s https://talksport.com/play/talksport2 | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[3]/text()' - | sed 's/amp;//')
         #onairtime=$(curl -s https://talksport.com/play/talksport | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-19) 
         
         # Check for BST or GMT
         if [ $(date +%Z) = "BST" ]
         then ST=1
         else ST=0
         fi
         
         onairtime1=$(curl -s https://talksport.com/play/talksport2 | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 1-8)
         onairtime2=$(curl -s https://talksport.com/play/talksport2 | xmllint --html --nowarning --xpath '/html/body/main/div[1]/div[2]/div[2]/div[2]/div[2]/text()' - | tail -c 31 | cut -c 11-20)
         onairtime3=$(date -d "$onairtime1 +$ST hour" "+%l:%M%P")
         onairtime4=$(date -d "$onairtime2 +$ST hour" "+%l:%M%P") 
         onairtime="$onairtime3 "-" $onairtime4"
         Onair_txt
}

On_Timesradio()
{
# # Get what's on Timesradio - grep characters between > and </h1> and between > and </p>
        onair=$(curl -s https://www.thetimes.com/radio/live-player | xmllint --html --nowarning --xpath '/html/body/section/div/div/div[2]/div[1]/div[1]/main/h1' - | grep -o -P '(?<=>).*(?=</h1>)')
        onairtime=$(curl -s https://www.thetimes.com/radio/live-player | xmllint --html --nowarning --xpath '/html/body/section/div/div/div[2]/div[1]/div[1]/main/div/div/p' - | grep -o -P '(?<=>).*(?=</p>)')
        Onair_txt
}

On_radioparadise()
#Get what's on radio paradise and download cover artist
{
        # Fetch JSON data from new API and save local copy
        curl -o ~/.config/radiotray-ng/bookmark_icons/now.json "https://api.radioparadise.com/api/now_playing?"
        
        # Extract cover_small URL from JSON
        chk_art=$(jq -r '.cover_small' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null)
        # Store previous coverart for comparison (if exists)
        if [ -f ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt ]; then
            prev_art=$(cat ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt)
        else
            prev_art=""
        fi
            
        # Check if the coverart urls match and, if not, get new coverart and resize to 110 width
        if [ "$prev_art" != "$chk_art" ] && [ -n "$chk_art" ] && [ "$chk_art" != "null" ]; then 
            curl -o ~/.config/radiotray-ng/bookmark_icons/rp_art "$chk_art"
            magick ~/.config/radiotray-ng/bookmark_icons/rp_art -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
            echo "$chk_art" > ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt
        fi
        
        # Extract artist and song title from JSON
        rpartist=$(jq -r '.artist' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null | sed 's/amp;//g')
        rpsongtitle=$(jq -r '.title' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null | sed 's/amp;//g')
        
        # echo artist and song to conky file
        echo "$rpartist" > ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo " - " >> ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo "$rpsongtitle" >> ~/.conky/conkyradiotray-ng/onair.txt
}

On_radioparadise_rock()
#Get what's on radio paradise and download cover artist
{
        # Fetch JSON data from new API and save local copy
        curl -o ~/.config/radiotray-ng/bookmark_icons/now.json "https://api.radioparadise.com/api/now_playing?chan=2"
        
        # Extract cover_small URL from JSON
        chk_art=$(jq -r '.cover_small' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null)
        # Store previous coverart for comparison (if exists)
        if [ -f ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt ]; then
            prev_art=$(cat ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt)
        else
            prev_art=""
        fi
            
        # Check if the coverart urls match and, if not, get new coverart and resize to 110 width
        if [ "$prev_art" != "$chk_art" ] && [ -n "$chk_art" ] && [ "$chk_art" != "null" ]; then 
            curl -o ~/.config/radiotray-ng/bookmark_icons/rp_art "$chk_art"
            magick ~/.config/radiotray-ng/bookmark_icons/rp_art -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
            echo "$chk_art" > ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt
        fi
        
        # Extract artist and song title from JSON
        rpartist=$(jq -r '.artist' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null | sed 's/amp;//g')
        rpsongtitle=$(jq -r '.title' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null | sed 's/amp;//g')
        
        # echo artist and song to conky file
        echo "$rpartist" > ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo " - " >> ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo "$rpsongtitle" >> ~/.conky/conkyradiotray-ng/onair.txt
}

On_radioparadise_mellow()
#Get what's on radio paradise and download cover artist
{
        # Fetch JSON data from new API and save local copy
        curl -o ~/.config/radiotray-ng/bookmark_icons/now.json "https://api.radioparadise.com/api/now_playing?chan=1"
        
        # Extract cover_small URL from JSON
        chk_art=$(jq -r '.cover_small' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null)
        # Store previous coverart for comparison (if exists)
        if [ -f ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt ]; then
            prev_art=$(cat ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt)
        else
            prev_art=""
        fi
            
        # Check if the coverart urls match and, if not, get new coverart and resize to 110 width
        if [ "$prev_art" != "$chk_art" ] && [ -n "$chk_art" ] && [ "$chk_art" != "null" ]; then 
            curl -o ~/.config/radiotray-ng/bookmark_icons/rp_art "$chk_art"
            magick ~/.config/radiotray-ng/bookmark_icons/rp_art -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
            echo "$chk_art" > ~/.config/radiotray-ng/bookmark_icons/prev_coverart.txt
        fi
        
        # Extract artist and song title from JSON
        rpartist=$(jq -r '.artist' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null | sed 's/amp;//g')
        rpsongtitle=$(jq -r '.title' ~/.config/radiotray-ng/bookmark_icons/now.json 2>/dev/null | sed 's/amp;//g')
        
        # echo artist and song to conky file
        echo "$rpartist" > ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo " - " >> ~/.conky/conkyradiotray-ng/onair.txt
        truncate --size -1 ~/.conky/conkyradiotray-ng/onair.txt
        echo "$rpsongtitle" >> ~/.conky/conkyradiotray-ng/onair.txt
}


lbc_uk='LBC UK'
lbc_london='LBC London'
lbc_news='LBC News'
gb_news='GB News'
times_radio='Times Radio'
#plan_rock='Planet Rock'
radio_paradise='Radio Paradise'
radio_paradise_rock='Radio Paradise Rock'
radio_paradise_mellow="Radio Paradise Mellow"
ragga='Raggakings'
talkradio='TalkRadio'
talksport='talkSPORT'
talksport2='talkSPORT 2'
fivelive='BBC Radio 5 Live'
radiostoke='BBC Radio Stoke'
bloomr='Bloomberg Radio'
#classicfm='Classic FM'
morow='Morow'
#audiophile='Audiophile Classical'
not_playing='(not playing)'

#Check for Radio Paradise or show radiotray image if status='Playing'
station=${st}
status=''
rp='Radio Paradise'
artist=${so: -0}
cadena=${st: -14}

if [ "$artist" = "$status" ]; 
then
title='antenna tower icon white'
#title='free white radio tower icon-18'
elif [ "$cadena" = "$rp" ]; 
then 
station='Radio Paradise'  
else 
title=$so
#title=""$ar" "-" "$so""
fi

#Check if station='(not playing)
query='(not playing)' 
output=${st: -13}   
if [ "$output" = "$query" ]; 
then 
station='(not playing)'
fi

#Check each station variable and use imagemagick magick command to resize image and copy to ~/.config/radiotray-ng/bookmark_icons/icon
case "$station" in 
    "$lbc_uk" )
        magick  ~/.config/radiotray-ng/bookmark_icons/lbc_round -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC
;;
    "$lbc_news" )
        magick  ~/.config/radiotray-ng/bookmark_icons/lbc_news -resize 135 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC_News
;;
    "$gb_news" )
        magick  ~/.config/radiotray-ng/bookmark_icons/GBN.png -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_GB_News
;;
    "$lbc_london" )
        magick ~/.config/radiotray-ng/bookmark_icons/lbc2 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_LBC
;;
    "$times_radio" )
        magick ~/.config/radiotray-ng/bookmark_icons/timesradio -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Timesradio
;;
    "$talkradio" )
        magick ~/.config/radiotray-ng/bookmark_icons/TalkRadio -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Talkradio
;;
    "$talksport" )
        magick ~/.config/radiotray-ng/bookmark_icons/talksport -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Talksport
;;
    "$talksport2" )
        magick ~/.config/radiotray-ng/bookmark_icons/talksport2 -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        On_Talksport2
;;
    "$fivelive" )
        magick ~/.config/radiotray-ng/bookmark_icons/5live -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
       
;;
    "$radiostoke" )
        magick ~/.config/radiotray-ng/bookmark_icons/radiostoke -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon
        
;;
    "$bloomr" )
        magick ~/.config/radiotray-ng/bookmark_icons/br -resize 110 ~/.config/radiotray-ng/bookmark_icons/icon    
;;
    "$radio_paradise" )
        On_radioparadise
;;
    "$radio_paradise_rock" )
        On_radioparadise_rock
;;
    "$radio_paradise_mellow" )
        On_radioparadise_mellow
;;
    #If status = 'not playing' don't do anything
    "$not_playing" )
;;
    #If any other case get albumart using miniatureGoogleImage
    *)
        # Set paths
        ICON_PATH="$HOME/.config/radiotray-ng/bookmark_icons/icon"
        HASH_FILE="/tmp/radiotray_hash"
        ARTIST_TITLE_FILE="$HOME/.conky/conkyradiotray-ng/artist_title.txt"
        
        # Generate hash from current artist and song
        current_hash=$(echo "$ar$so" | md5sum | cut -d' ' -f1)
        saved_hash=""
        
        # Read saved hash if file exists
        if [ -f "$HASH_FILE" ]; then
            saved_hash=$(cat "$HASH_FILE")
        fi
        
        # Check if track has changed
        if [ "$saved_hash" != "$current_hash" ]; then
            # Track changed - need to get new album art
            if [ -n "$ar" ] && [ -n "$so" ] && [ "$ar" != "null" ] && [ "$so" != "null" ]; then
                
                # Save artist and title to file
                echo "$ar - $so" | fold -s -w80 > "$ARTIST_TITLE_FILE"
                
                # Prepare search string
                title_search=$(echo "$ar - $so" | sed 's/ /+/g' | sed 's/&/%26/g' | sed 's/#/%23/g' | sed 's/:/%3A/g' | sed 's/;/%3B/g' | sed 's/,/%2C/g' | sed 's/\[/%5B/g' | sed 's/\]/%5D/g')
                
                # Get image URL from Google
                linkMiniature=$(wget -U 'Googlebot-Image/1.0' -qO - "www.google.co.uk/search?q=$title_search\&tbm=isch" | awk -v RS='[[:blank:]]' '/^src=/' | awk 'NR==2' | cut -c6- | sed 's/.\{11\}$//')
                
                # Download and process image if URL is valid
                if [ -n "$linkMiniature" ] && [ "$linkMiniature" != "http://" ] && [ "$linkMiniature" != "https://" ]; then
                    wget -O /tmp/miniatureGoogleImage "$linkMiniature" 2>/dev/null
                    
                    # Verify download succeeded (file exists and has content)
                    if [ -f /tmp/miniatureGoogleImage ] && [ -s /tmp/miniatureGoogleImage ]; then
                        # Check if it's a valid image (optional but recommended)
                        if file /tmp/miniatureGoogleImage | grep -q "image"; then
                            magick /tmp/miniatureGoogleImage -resize 110 "$ICON_PATH"
                            # Save hash ONLY after successful download
                            echo "$current_hash" > "$HASH_FILE"
                        fi
                    fi
                fi
            fi
        fi
        # If hash matches, album art is already correct - do nothing
;;
esac

# Show artist and title info or "No Info"
if [ "$lbc_uk" = "$st" ] || [ "$lbc_news" = "$st" ]  || [ "$gb_news" = "$st" ] || [ "$lbc_london" = "$st" ] || [ "$radio_paradise" = "$st" ]  || [ "$radio_paradise_rock" = "$st" ] || [ "$radio_paradise_mellow" = "$st" ] || [ "$talksport" = "$st" ] || [ "$times_radio" = "$st" ] || [ "$talkradio" = "$st" ]; #|| [ "$talksport2" = "$st" ] 
    then
    conkytitle=$(cat ~/.conky/conkyradiotray-ng/onair.txt)
 
elif [ "$talkradio" = "$st" ] || [ "$playing" = "$so" ]
    then 
    conkytitle='No info'
    
else 
    conkyspacer=" - "
    conkytitle="$ar""$conkyspacer""$so"
    conkyartist=$ar
    
fi

echo "$conkytitle"

exit 0
