#!/bin/bash 
if pidof -x $(basename radiotray) > /dev/null 
then 
st=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio)
so=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray getCurrentMetaData| fold -s -w150) 
status='Playing' 
artist=${so: -7}   
if [ "$artist" = "$status" ]; 
then 
title='No info'   
else 
title=$so 
fi
fi
echo $title 
exit 0
