#!/bin/bash
if pidof -x "$(basename radiotray)" > /dev/null 
then
st=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio)
so=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray getCurrentMetaData| fold -s -w150)
lbc_uk='LBC UK'
lbc_london='LBC London'
plan_rock='Planet Rock'
kfi='KFI'
twit='TWiT.am'
fivelive='5live'
radiofour='Radio 4'
radiofourextra='Radio 4 Extra'
radiostoke='Radio Stoke'
radio_paradise='Radio Paradise' 
ragga='Raggakings'
talkradio='TalkRadio'
not_playing='(not playing)'

station=${st}
status='Playing'
rp='Radio Paradise'
artist=${so: -7}
cadena=${st: -14} 
if [ "$artist" = "$status" ]; 
then
#title='radiotray icon'
title='hashtag/radiotray'
#title='black'
elif [ "$cadena" = "$rp" ]; 
then 
station='Radio Paradise'  
else 
title=$so 
fi

query='(not playing)' 
output=${st: -13}   
if [ "$output" = "$query" ]; 
then 
station='(not playing)'
fi

echo "$title" | fold -s -w80 > ~/.conky/conkyradiotray/artist_title.txt

title=$(head -1 ~/.conky/conkyradiotray/artist_title.txt)
linkMiniature=$(wget -U'Googlebot-Image/1.0' -qO - "www.google.co.uk/search?q=$title\&tbm=isch" | perl -pe 's!.*?<img .*?src="([^"]*)".*!$1!')

case "$station" in 
    "$lbc_uk" )
        convert ~/.local/share/radiotray/lbc -resize 110 ~/.local/share/radiotray/icon
;;
    "$lbc_london" )
        convert ~/.local/share/radiotray/lbc2 -resize 110 ~/.local/share/radiotray/icon
;;
    "$kfi" )
        convert ~/.local/share/radiotray/kfi -resize 110 ~/.local/share/radiotray/icon
;;
    "$twit" )
        convert ~/.local/share/radiotray/twit -resize 110 ~/.local/share/radiotray/icon
;;
    "$fivelive" )
        convert ~/.local/share/radiotray/5live -resize 110 ~/.local/share/radiotray/icon
;;
    "$radiofour" )
        convert ~/.local/share/radiotray/radio4 -resize 110 ~/.local/share/radiotray/icon
;;
    "$radiofourextra" )
        convert ~/.local/share/radiotray/radio4extra -resize 110 ~/.local/share/radiotray/icon
;;
    "$radiostoke" )
        convert ~/.local/share/radiotray/radiostoke -resize 110 ~/.local/share/radiotray/icon
;;
    "$talkradio" )
        convert ~/.local/share/radiotray/talkradio -resize 110 ~/.local/share/radiotray/icon
;;
    "$plan_rock" )
        convert ~/.local/share/radiotray/planrock -resize 110 ~/.local/share/radiotray/icon
;;
    "$ragga" )
        convert ~/.local/share/radiotray/ragga -resize 110 ~/.local/share/radiotray/icon
;;
    "$radio_paradise" )
        curl -o ~/.local/share/radiotray/now.xml http://radioparadise.com/xml/now.xml
        art=$(awk -F '[<>]' '/coverart/{print $3}' ~/.local/share/radiotray/now.xml)
        wget -O ~/.local/share/radiotray/rp_art "$art"
        convert ~/.local/share/radiotray/rp_art -resize 110 ~/.local/share/radiotray/icon
;;
    "$not_playing" )
;;
    *)
        #cp -f ~/.local/share/radiotray/radiotray  ~/.local/share/radiotray/icon
        wget -qO miniatureGoogleImage "$linkMiniature"
        convert ~/miniatureGoogleImage -resize 110 ~/.local/share/radiotray/icon
;;
esac
fi
exit 0


