#!/bin/bash
if pidof -x "$(basename radiotray)" > /dev/null 
then

#Populate $st with current station, $so with current artist and song and define station name variables
st=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio)
so=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray getCurrentMetaData| fold -s -w150)

lbc_uk='LBC UK'
lbc_london='LBC London'
plan_rock='Planet Rock'
kfi='KFI'
twit='TWiT.am'
fivelive='5live'
radiofour='Radio 4'
radiofourextra='Radio 4 Extra'
radiostoke='Radio Stoke'
radio_paradise='Radio Paradise' 
ragga='Raggakings'
talkradio='TalkRadio'
not_playing='(not playing)'

#Check for Radio Paradise or show radiotray image if status='Playing'
station=${st}
status='Playing'
rp='Radio Paradise'
artist=${so: -7}
cadena=${st: -14} 
if [ "$artist" = "$status" ]; 
then
#title='radiotray icon'
title='hashtag/radiotray'
#title='black'
elif [ "$cadena" = "$rp" ]; 
then 
station='Radio Paradise'  
else 
title=$so 
fi

#Check if station='(not playing)
query='(not playing)' 
output=${st: -13}   
if [ "$output" = "$query" ]; 
then 
station='(not playing)'
fi

#Read the first line of artist_title.txt for artist & song title and populate $title_read
title_read=$(head -1 ~/.conky/conkyradiotray/artist_title.txt)

#set $linkMiniature to download mini image based on $title
linkMiniature=$(wget -U'Googlebot-Image/1.0' -qO - "www.google.co.uk/search?q=$title\&tbm=isch" | perl -pe 's!.*?<img .*?src="([^"]*)".*!$1!')

#Check each station variable and use imagemagick convert command to resize image and copy to ~/.local/share/radiotray/icon
case "$station" in 
    "$lbc_uk" )
        convert ~/.local/share/radiotray/lbc -resize 110 ~/.local/share/radiotray/icon
;;
    "$lbc_london" )
        convert ~/.local/share/radiotray/lbc2 -resize 110 ~/.local/share/radiotray/icon
;;
    "$kfi" )
        convert ~/.local/share/radiotray/kfi -resize 110 ~/.local/share/radiotray/icon
;;
    "$twit" )
        convert ~/.local/share/radiotray/twit -resize 110 ~/.local/share/radiotray/icon
;;
    "$fivelive" )
        convert ~/.local/share/radiotray/5live -resize 110 ~/.local/share/radiotray/icon
;;
    "$radiofour" )
        convert ~/.local/share/radiotray/radio4 -resize 110 ~/.local/share/radiotray/icon
;;
    "$radiofourextra" )
        convert ~/.local/share/radiotray/radio4extra -resize 110 ~/.local/share/radiotray/icon
;;
    "$radiostoke" )
        convert ~/.local/share/radiotray/radiostoke -resize 110 ~/.local/share/radiotray/icon
;;
    "$talkradio" )
        convert ~/.local/share/radiotray/talkradio -resize 110 ~/.local/share/radiotray/icon
;;
    "$plan_rock" )
        convert ~/.local/share/radiotray/planrock -resize 110 ~/.local/share/radiotray/icon
;;
    "$ragga" )
        convert ~/.local/share/radiotray/ragga -resize 110 ~/.local/share/radiotray/icon
;;
    "$radio_paradise" )
        
        #Populate $chk_art with the coverart url
        chk_art=$(awk -F '[<>]' '/coverart/{print $3}' ~/.local/share/radiotray/now.xml)
        
        #Download now.xml and save local copy
        curl -o ~/.local/share/radiotray/now.xml http://radioparadise.com/xml/now.xml
        
        #Populate $chk_art2 with the coverart url from local copy of now.xml
        chk_art2=$(awk -F '[<>]' '/coverart/{print $3}' ~/.local/share/radiotray/now.xml)
        
            #Check if the coverart urls match and, if not, get new coverart and resize to 130 width
            if 
                [ "$chk_art" != "$chk_art2" ]; 
            then 
                art=$(awk -F '[<>]' '/coverart/{print $3}' ~/.local/share/radiotray/now.xml)
                wget -O ~/.local/share/radiotray/rp_art "$art"
                convert ~/.local/share/radiotray/rp_art -resize 110 ~/.local/share/radiotray/icon
            fi
    
;;
    #If status = 'not playing' don't do anything
    "$not_playing" )
;;
    #If any other case get albumart using miniatureGoogleImage
    *)
        #Check if albumart is already downloaded, if not, populate artist_title.txt with artist & song title, then download albumart and convert to icon and resize it
        if
        [ "$title_read" != "$title" ];
        then
        echo "$title" | fold -s -w80 > ~/.conky/conkyradiotray/artist_title.txt
        wget -qO miniatureGoogleImage "$linkMiniature"
        convert ~/miniatureGoogleImage -resize 110 ~/.local/share/radiotray/icon
        fi
;;
esac
fi

exit 0


