#!/bin/bash 
st=$(qdbus net.sourceforge.radiotray /net/sourceforge/radiotray net.sourceforge.radiotray.getCurrentRadio)
lbc_uk='LBC UK'
lbc_london='LBC London'
plan_rock='Planet Rock'
kfi='KFI'
twit='TWiT.am'
ragga='Raggakings'
fivelive='5live'
radiofour='Radio 4'
radiofourextra='Radio 4 Extra'
radiostoke='Radio Stoke'
radio_paradise='Radio Paradise' 
soma='Space Station Soma'
crl='Classic Rock Lounge'
pingrad='Pinguin Radio'
hr80s='Hard Rockin 80s'
talkradio='TalkRadio'
big80s='Big 80s Metal'

station=${st}

title=$(head -1 ~/.conky/conkyradiotray/artist_title.txt)
linkMiniature=$(wget -U'Googlebot-Image/1.0' -qO - "www.google.co.uk/search?q=$title\&tbm=isch" | perl -pe 's!.*?<img .*?src="([^"]*)".*!$1!')
wget -qO miniatureGoogleImage $linkMiniature


case "$station" in 
    "$lbc_uk" )
        cp -f /home/swipe/.local/share/radiotray/lbc  /home/swipe/.local/share/radiotray/icon
;;
    "$lbc_london" )
        cp -f /home/swipe/.local/share/radiotray/lbc2  /home/swipe/.local/share/radiotray/icon
;;
    "$kfi" )
        cp -f /home/swipe/.local/share/radiotray/kfi  /home/swipe/.local/share/radiotray/icon
;;
    "$twit" )
        cp -f /home/swipe/.local/share/radiotray/twit  /home/swipe/.local/share/radiotray/icon
;;
    "$fivelive" )
        cp -f /home/swipe/.local/share/radiotray/5live  /home/swipe/.local/share/radiotray/icon
;;
    "$radiofour" )
        cp -f /home/swipe/.local/share/radiotray/radio4  /home/swipe/.local/share/radiotray/icon
;;
    "$radiofourextra" )
        cp -f /home/swipe/.local/share/radiotray/radio4extra  /home/swipe/.local/share/radiotray/icon
;;
    "$radiostoke" )
        cp -f /home/swipe/.local/share/radiotray/radiostoke  /home/swipe/.local/share/radiotray/icon
;;
    "$talkradio" )
        cp -f /home/swipe/.local/share/radiotray/talkradio  /home/swipe/.local/share/radiotray/icon
;;
    "$radio_paradise" )
;;
    *)
        #cp -f /home/swipe/.local/share/radiotray/radiotray  /home/swipe/.local/share/radiotray/icon
        convert ~/miniatureGoogleImage ~/.local/share/radiotray/icon
;;
esac

exit 0


