#!/bin/bash

first_cover=""

	new_cover=`playerctl -i plasma-browser-integration metadata --format '{{ mpris:artUrl }}'`
	if [ "$new_cover" != "$first_cover" ]
	then
		first_cover="$new_cover"
		magick $new_cover ~/.conky/conkytidal/last_album_pic.png
	fi
	sleep 1
