#!/bin/bash

first_album=""

	new_album=`playerctl -i plasma-browser-integration metadata --format '{{ album }}'`
	if [ "$new_album" != "$first_album" ]
	then
		first_album="$new_album"
		echo "$new_album"
	fi
	sleep 1
