#!/bin/bash

first_artist=""

	new_artist=`playerctl -i plasma-browser-integration metadata --format '{{ artist }}'`
	if [ "$new_artist" != "$first_artist" ] 
	then
		first_artist="$new_artist"
		echo "$new_artist"
	fi
	sleep 1
